
project_id = "fwneovyqetoglcrzanig"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.ai-services]
verify_jwt = false
