// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epneueqmwrsafacwrpgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwbmV1ZXFtd3JzYWZhY3dycGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTg2OTUsImV4cCI6MjA1OTk5NDY5NX0.1IUVH6dXWxDOfeftUGGhbzaBh8WoZhq9FQvBOo1rT38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);