// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fwneovyqetoglcrzanig.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3bmVvdnlxZXRvZ2xjcnphbmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTQ2MjMsImV4cCI6MjA2MDk3MDYyM30.Mm84nsVf8iP3YDOJlk6oRhhWCZ8_ETkjul7MC9yWbJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);